const c = async () => throw Error('hello');