const [error, data] = tryCatch(fn);
const [] = hello;

for (const [] of hello)
    x();

